name: Publish lre-react

on:
  [push]

jobs:
 # build:
  #  runs-on: ubuntu-latest
   # steps:
    #  - uses: actions/checkout@v2
     # - uses: actions/setup-node@v1
      #  with:
       #   node-version: 12
     # - run: npm ci
     # - run: npm test

  publish-gpr:
   # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@lrewater'
      # - run: npm ci
      - run: yarn install --frozen-lockfile
      - run: yarn build
      #- run: npm publish
      - name: release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
